### ISSUE TITLE
Question : Any reason render is abstract inside the TemplateCore

### ISSUE THREAD

**Issue by harikt** [qiqphp/qiq#11]
Can we move the render method from `Template` class to `TemplateCore` ?

Any specific reason for not keeping it inside `TemplateCore` .

This probably is also related to discussion https://github.com/qiqphp/qiq/issues/8 different compiler, passing additional factories to helperlocator if https://github.com/qiqphp/qiq/pull/9 is merged etc.

**Comment by pmjones** [comment]
Hi @harikt -- thanks for your patience.

The purpose of having it implemented in Template, is so that it does not have access to private properties in TemplateCore. Otherwise those properties would be available inside templates.

Having said that, I don't recall why I declared it as abstract in TemplateCore; looking at it now, it might as well have been left out of TemplateCore entirely and implemented only in Template.

Does that help at all?

**Comment by harikt** [comment]
I do want to look back, don't recall what all stuffs I have in mind at the time. Bit busy, so will get back when I get some time.

**Comment by pmjones** [comment]
> I don't recall why I declared it as abstract in TemplateCore

Oh -- because it gets called from TemplateCore::__invoke().

@harikt Any other thoughts here?

**Comment by harikt** [comment]
Hey @pmjones I have been digging into the conversation. But I guess, I lost what I was trying to get from. ( Due to my poor communication / context in the content ) . May be we can close this issue for now. I can re-open in case I need the feature.

**Comment by pmjones** [comment]
Very good, sir -- reopen as necessary!
